### ISSUE TITLE
Blank screen when starting game

### ISSUE THREAD

**Issue by naclander** [tuomount/Open-Realms-of-Stars#179]
This game looks super cool, and I've gone ahead and cloned the repo to my local machine.

After running  `mvn install`, I launch the game and get the following error. A new window pops up for the game buut then game screen is blank ( just white ). Exception below:

```
~/Projects/games/Open-Realms-of-Stars/target(master) » java -jar Open-Realm-of-Stars-0.5.18Alpha.jar                                                                                                                                       0s 
Adjust frame, since OS's UI component require their own space from JFrame.
Adjusting X: 4 Adjusting Y: 31
Exception in thread "main" java.lang.NoClassDefFoundError: com/jcraft/jogg/Page
	at org.openRealmOfStars.audio.music.OggPlayer.<init>(OggPlayer.java:52)
	at org.openRealmOfStars.audio.music.MusicPlayer.play(MusicPlayer.java:247)
	at org.openRealmOfStars.audio.music.MusicPlayer.play(MusicPlayer.java:212)
	at org.openRealmOfStars.game.Game.<init>(Game.java:360)
	at org.openRealmOfStars.game.Game.main(Game.java:1304)
Caused by: java.lang.ClassNotFoundException: com.jcraft.jogg.Page
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/jcraft/jogg/Page
	at org.openRealmOfStars.audio.music.OggPlayer.<init>(OggPlayer.java:52)
	at org.openRealmOfStars.audio.music.MusicPlayer.play(MusicPlayer.java:247)
	at org.openRealmOfStars.audio.music.MusicPlayer.play(MusicPlayer.java:212)
	at org.openRealmOfStars.audio.music.MusicPlayer.playGameMusic(MusicPlayer.java:352)
	at org.openRealmOfStars.audio.music.MusicPlayer.handleMusic(MusicPlayer.java:384)
	at org.openRealmOfStars.game.Game.actionPerformed(Game.java:1447)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by tuomount** [comment]
This stack trace is because you envinronment is missing JCraft Ogg library. Instead of running the jar, unzip the Open-Realm-of-Stars-0.5.18Alpha-pack.zip, it contains all the file required for running and contains the same files as the release version. I'll double check the instructions that user needs to unzip the zip and use that.

**Comment by naclander** [comment]
Shouldn't the JCraft Ogg Library be installed by Maven, as part of handling missing dependencies?

**Comment by naclander** [comment]
Anyway, that seems to work, I would just add these instructions to the README. Thanks for the help.

**Comment by tuomount** [comment]
Added better instructions to README. Closing this issue now.
