### ISSUE TITLE
Game Crashes When Moving Unit

### ISSUE THREAD

**Issue by naclander** [tuomount/Open-Realms-of-Stars#180]
When trying to move a unit somewhere ( must have been my second turn ), after I set the route and clicked "end trun", the game was frozen on the Enemy Turn waiting screen, and I got the following stack trace:

```
~/Projects/games/Open-Realms-of-Stars/target/Open-Realm-of-Stars-0.5.18Alpha(master) » java -jar Open-Realm-of-Stars-0.5.18Alpha.jar                                                                                                       0s 
Adjust frame, since OS's UI component require their own space from JFrame.
Adjusting X: 4 Adjusting Y: 31
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.openRealmOfStars.player.PlayerInfo.getUnchartedSector(PlayerInfo.java:764)
	at org.openRealmOfStars.AI.Mission.MissionHandling.handleColonyExplore(MissionHandling.java:306)
	at org.openRealmOfStars.game.States.AITurnView.handleMissions(AITurnView.java:225)
	at org.openRealmOfStars.game.States.AITurnView.handleAIFleet(AITurnView.java:888)
	at org.openRealmOfStars.game.States.AITurnView.handleActions(AITurnView.java:1102)
	at org.openRealmOfStars.game.Game.actionPerformed(Game.java:1552)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

The game now appears to be stuck.

**Comment by tuomount** [comment]
Oops, looks like new colony mission broke something. This seems to be related to #160 .

**Comment by tuomount** [comment]
Fixed the crashing bug. You cannot load your save because save is already corrupted, please start a new game. Problem was that sun information was not stored for colony explore mission. If you verify that it does not crash any more, you can close this issue.

**Comment by naclander** [comment]
Yes, I guess technically the game doesn't crash anymore if the route isn't reachable. Except now if they ship can't reach somewhere, after clicking "end turn" it just won't move ( causing a turn to be waisted ). 

I think informing the player whether a route is reachable ( at least currently ) before ending their turn is a much better experience than having the ship silently not move. 

This problem would obviously get exponentially worse if you're moving dozens of ships. 

Technically the original issue is resolved, if you wanted to track the other issue I mentioned in a new github issue that works for me as well, I'll let you resolve the ticket or use it to track the new issue I mentioned, up to you. Thanks again.

**Comment by tuomount** [comment]
Actual crashed happened in AI's turn not on human player turn. 

If your route has finished and you have moves left, there is a notification at next turn, that you didn't move your ship. When moving your fleets with Route it means that ships is travelling with FTL. Regular move (with arrow keys or right clicking the next square, uses fleet's non FTL moves). FTL moves are done in end of the turn and players cannot know if fleet can really do that move(unless obviously trying to move inside sun or gas giant that it cannot do that).

In general wasting one turn not in move is not that critical as for single fleet(Unless you are hurry to move your fleet to defend some other planet).

But I'll close this issue and keep tracking the issue #160.

**Comment by naclander** [comment]
Not sure I agree with that from a usability perspective. I'm just coming at this from a perspective of a new user. It might have been that there was so notification that my route was invalid, but it was not clearly visible to me. 

From my perspective, some routes worked, and some routes didn't ( for example, going into, through, or around a sun giant didn't work ). As a user, it would be nice to know those routes can't happen before I click end turn. 

I'm just giving you my impression and the problems I ran into as a new user.

**Comment by naclander** [comment]
Also, 

> In general wasting one turn not in move is not that critical as for single fleet(Unless you are hurry to move your fleet to defend some other planet).

It might not be critical, but its A) not obvious to new users it's not that critical and more importantly B) is really annoying.

**Comment by tuomount** [comment]
Hmm, user could get indication if route ends into sun or already visible gas giant that route is illegal. But if blocker is not visible then obviously it should not warn about it since FTL travel can be used also as a exploration.

At the moment route just takes shortest route to from A to B and it does not mind about obstacles in it way. If it cannot get through it will notify it during next turn and then player has to manually go through it. Also AI uses it this way.

Other option could be that FTL is not for exploration at all and routing takes only place with sectors which are already explored by the player.

Obviously routing and move fleets is one thing which should be covered in tutorial, but I haven't started it since not all the features are ready in the game.
