### ISSUE TITLE
Improve error loggin on exceptions

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#289]
If exception error logging happens, it does not tell where it happened. This makes debugging more difficult. It should tell where the exception happened.

**Comment by afiuorio** [comment]
Hi,

I've searched a little in your source code and I've seen you are using a couple of hand-made loggers. In my opinion it's probably better to switch to something like log4j: this will give you an higher control of logging messages, can have logging levels automatically and configurable, the logger are easily parsable since they are a standard.

I've checked and it doesn't seems a long work to do the switch, so if you want I can do it with a single pull request.

**Comment by tuomount** [comment]
Seems that log4j is Apache license and my project is under GPL2 and those two licenses are not compatible.
I was thinking to change method in ErrorLogger.java
```java
public static void log(final Exception exception)
```
 something that one could give String and Exception and it would say where the call was made.
Normally game isn't logging anything unless something goes wrong.

**Comment by afiuorio** [comment]
You are absolutely right, I didn't noticed this project is under GPL2. 

It should be possibile to not change the log method signature, if I remember correctly there should be a way to get the line number from the stacktrace in the excepion. Working on it.

**Comment by tuomount** [comment]
After accepting the pull request, I started to test new logging with problem I encountered earlier and noticed that it is missing the else clause.

I got following log:
´´´
org.openRealmOfStars.player.PlayerInfo - 1177 - 256
org.openRealmOfStars.player.PlayerInfo - 1177 - 256
org.openRealmOfStars.player.PlayerInfo - 1177 - 256
null
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0
	at org.openRealmOfStars.utilities.ErrorLogger.log(ErrorLogger.java:50)
	at org.openRealmOfStars.player.PlayerInfo.getSectorVisibility(PlayerInfo.java:1179)
	at org.openRealmOfStars.gui.mapPanel.Minimap.Minimap.drawMinimap(Minimap.java:249)
	at org.openRealmOfStars.gui.mapPanel.MapPanel.drawMap(MapPanel.java:365)
	at org.openRealmOfStars.game.States.StarMapView.handleActions(StarMapView.java:420)
	at org.openRealmOfStars.game.Game.actionPerformedStarMap(Game.java:1930)
	at org.openRealmOfStars.game.Game.actionPerformed(Game.java:1992)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
´´´

Now that null is being printed at here
´´´java
 if (exception.getStackTrace().length == 0) {
      //This should never happens but you never know...
      ErrorLogger.log(exception.getMessage());
    }
´´´
and after that it still continues to getting first element from stack trace which had zero element. Would you willing to be fix this?

**Comment by tuomount** [comment]
But if I had this print earlier, it would helped me to fix the issue in minimap since before this change all I got was 256 text couple of times and then lot's null texts.

By the way print would be better if it would say line or row in the second column. Could you please change that too?

**Comment by afiuorio** [comment]
Oh, sorry, I made that commit with haste and I didn't thought about that. I will fix it as soon as possible.

**Comment by tuomount** [comment]
Done now and works. Closing.
