### ISSUE TITLE
Galaxy should have center

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#319]
Galaxy should have a center with black hole. Basically this would be just a blocked tiles in center of galaxy.

**Comment by tuomount** [comment]
Works now.

**Comment by tuomount** [comment]
This happened this when view the history:
```
Exception in thread "AWT-EventQueue-0" java.awt.image.RasterFormatException: x lies outside raster
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:461)
	at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
	at org.openRealmOfStars.gui.mapPanel.MapPanel.updateBlackHoleEffect(MapPanel.java:389)
	at org.openRealmOfStars.gui.mapPanel.MapPanel.drawHistoryMap(MapPanel.java:950)
	at org.openRealmOfStars.game.States.HistoryView.handleAction(HistoryView.java:324)
	at org.openRealmOfStars.game.Game.actionPerformed(Game.java:2391)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by tuomount** [comment]
After latest commit history view did not broke anymore. Closing.
