### ISSUE TITLE
NPE when fleet has been removed from starmap

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#60]
There is possible NPE when fleet has been removed but it is still in fleetMap.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.openRealmOfStars.gui.mapPanel.MapPanel.drawMap(MapPanel.java:421)
	at org.openRealmOfStars.game.States.StarMapView.handleActions(StarMapView.java:302)
	at org.openRealmOfStars.game.Game.actionPerformed(Game.java:951)

**Comment by tuomount** [comment]
Fixed with simple null check:
if (fleet != null && info.getSectorCloakDetection(i + cx, j + cy)
              >= fleet.getFleetCloackingValue()) {
