### ISSUE TITLE
Null Pointer on artifact research

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#763]
Null pointer exception:
java.lang.NullPointerException
	at org.openRealmOfStars.player.artifact.ArtifactLists.updateResearchPointByTurn(ArtifactLists.java:341)
	at org.openRealmOfStars.game.state.AITurnView.handleAiTurn(AITurnView.java:3788)
	at org.openRealmOfStars.game.GameTest.testRunFullGameLongWith12Realms(GameTest.java:407)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Also it looks like artifact research is done even there are no artifacts left to study. This also needs to be fixed.

**Comment by tuomount** [comment]
Hasn't happened anymore. Closing
