### ISSUE TITLE
Null pointer on exploring pirate lair

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#765]
It is possible to get null pointer when exploring pirate lair:

testRunFullGames(org.openRealmOfStars.game.GameTest)  Time elapsed: 4.403 sec  <<< ERROR!
java.lang.NullPointerException
        at org.openRealmOfStars.player.combat.Combat.<init>(Combat.java:265)
        at org.openRealmOfStars.player.combat.Combat.<init>(Combat.java:245)
        at org.openRealmOfStars.mapTiles.anomaly.SpaceAnomaly.createAnomalyEvent(SpaceAnomaly.java:353)
        at org.openRealmOfStars.game.Game.fleetMakeMove(Game.java:910)
        at org.openRealmOfStars.ai.mission.MissionHandling.moveFleetRegular(MissionHandling.java:2411)
        at org.openRealmOfStars.ai.mission.MissionHandling.makeRegularMoves(MissionHandling.java:2529)
        at org.openRealmOfStars.ai.mission.MissionHandling.handleExploring(MissionHandling.java:673)
        at org.openRealmOfStars.game.state.AITurnView.handleMissions(AITurnView.java:323)
        at org.openRealmOfStars.game.state.AITurnView.handleAIFleet(AITurnView.java:1669)
        at org.openRealmOfStars.game.state.AITurnView.handleAiTurn(AITurnView.java:3762)
        at org.openRealmOfStars.game.GameTest.testRunFullGames(GameTest.java:438)

**Comment by tuomount** [comment]
Works now. Closing.
